# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "base"

  config.vm.host_name = "server-protecter"

  config.vm.network :private_network,ip:"192.168.50.5"

  config.vm.synced_folder "../../", "/var/www/server-protecter", create: true, group: "www-data", owner: "www-data"

  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--memory", 1024]
    vb.customize [ "modifyvm", :id, "--name", "server-protecter"]
  end

  config.vm.provision "chef_solo" do |chef|
  chef.cookbooks_path = ["cookbooks"]
  chef.add_recipe "server-protecter::default" 
  end
end
